# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('lorawan-5g-integration-example', ['lorawan-5g-integration','lorawan','csma'])
    obj.source = 'lorawan-5g-integration-example.cc'

